// ============================================
// POST /api/export/integrated-skills
// 匯出 Integrated Skills 完整報告 (DOCX — 支援中英文)
// ============================================

import { NextRequest, NextResponse } from 'next/server';
import { logger } from '@/shared/logger/logger';

interface ExportData {
  listeningContent?: string;
  dataFileSources?: { type: string; title: string; content: string }[];
  noteTakingGuide?: { question: string; hint: string }[];
  writingTask?: string;
  taskType?: string;
  studentNotes?: string;
  studentWriting?: string;
  analysis?: Record<string, unknown>;
}

async function generateDOCX(data: ExportData): Promise<Buffer> {
  const { Document, Packer, Paragraph, TextRun, HeadingLevel, Table, TableRow, TableCell, WidthType, BorderStyle } = await import('docx');

  const children: any[] = [];
  const heading = (text: string, level: typeof HeadingLevel.HEADING_1 | typeof HeadingLevel.HEADING_2) =>
    new Paragraph({ heading: level, children: [new TextRun(text)], spacing: { before: 300, after: 100 } });
  const para = (text: string, opts?: { color?: string; size?: number; italics?: boolean; bold?: boolean }) =>
    new Paragraph({ children: [new TextRun({ text, ...opts })], spacing: { after: 100 } });
  const sep = () => new Paragraph({ spacing: { after: 200 }, children: [] });

  // Title
  children.push(new Paragraph({ heading: HeadingLevel.TITLE, children: [new TextRun('DSE Integrated Skills Report')], spacing: { after: 200 } }));
  children.push(para('Generated by AI English Platform', { color: '888888', size: 20, italics: true }));
  children.push(sep());

  // Writing Task
  if (data.writingTask) {
    children.push(heading('📝 Writing Task', HeadingLevel.HEADING_1));
    if (data.taskType) children.push(para(`Type: ${data.taskType}`));
    children.push(para(data.writingTask));
    children.push(sep());
  }

  // Listening Content
  if (data.listeningContent) {
    children.push(heading('🎧 Listening Content', HeadingLevel.HEADING_1));
    children.push(para(data.listeningContent, { size: 18, color: '666666' }));
    children.push(sep());
  }

  // Data File
  if (data.dataFileSources?.length) {
    children.push(heading('📁 Data File', HeadingLevel.HEADING_1));
    for (const src of data.dataFileSources) {
      children.push(heading(`[${src.type}] ${src.title}`, HeadingLevel.HEADING_2));
      children.push(para(src.content, { size: 18, color: '666666' }));
    }
    children.push(sep());
  }

  // Note-taking Guide
  if (data.noteTakingGuide?.length) {
    children.push(heading('📋 Note-taking Guide', HeadingLevel.HEADING_1));
    for (const item of data.noteTakingGuide) {
      children.push(para(`Q: ${item.question}`, { bold: true }));
      children.push(para(`Hint: ${item.hint}`, { size: 18, color: '888888', italics: true }));
    }
    children.push(sep());
  }

  // Student Notes
  if (data.studentNotes) {
    children.push(heading('✏️ Student Note-taking', HeadingLevel.HEADING_1));
    children.push(new Paragraph({
      children: [new TextRun(data.studentNotes)],
      spacing: { after: 200 },
      border: { left: { style: BorderStyle.SINGLE, color: 'f59e0b', size: 6 } },
    }));
    children.push(sep());
  }

  // Student Writing
  if (data.studentWriting) {
    children.push(heading('📄 Student Writing', HeadingLevel.HEADING_1));
    children.push(new Paragraph({
      children: [new TextRun(data.studentWriting)],
      spacing: { after: 200 },
      border: { left: { style: BorderStyle.SINGLE, color: '7c3aed', size: 6 } },
    }));
    children.push(sep());
  }

  // AI Analysis
  const a = data.analysis;
  if (a) {
    children.push(heading('🤖 AI Analysis', HeadingLevel.HEADING_1));
    children.push(sep());

    // Scores table
    const scores: [string, string][] = [
      ['Overall Score', `${a.overallScore}%`],
      ['Listening Accuracy', `${a.listeningAccuracy ?? '-'}%`],
      ['Content Completeness', `${a.contentCompleteness ?? '-'}%`],
      ['Language Accuracy', `${a.languageAccuracy ?? '-'}%`],
      ['Organization & Clarity', `${a.organizationClarity ?? '-'}%`],
    ];
    if (a.estimatedLevel) scores.push(['Estimated Level', String(a.estimatedLevel)]);

    children.push(new Table({
      rows: scores.map(([label, val]) => new TableRow({
        children: [
          new TableCell({ children: [new Paragraph({ children: [new TextRun({ text: label, bold: true })] })], width: { size: 4500, type: WidthType.DXA } }),
          new TableCell({ children: [new Paragraph({ children: [new TextRun(val)] })] }),
        ],
      })),
      width: { size: 100, type: WidthType.PERCENTAGE },
    }));
    children.push(sep());

    // Captured/Missed Points
    const captured = (a.capturedPoints as string[]) || [];
    const missed = (a.missedPoints as string[]) || [];
    if (captured.length) {
      children.push(heading(`✅ Captured Points (${captured.length})`, HeadingLevel.HEADING_2));
      for (const pt of captured) children.push(para(`✓ ${pt}`));
    }
    if (missed.length) {
      children.push(heading(`❌ Missed Points (${missed.length})`, HeadingLevel.HEADING_2));
      for (const pt of missed) children.push(para(`✗ ${pt}`));
    }
    children.push(sep());

    // Grammar errors
    const grammarErrors = (a.grammarErrors as any[]) || [];
    if (grammarErrors.length) {
      children.push(heading('🔴 Grammar Errors', HeadingLevel.HEADING_2));
      for (const e of grammarErrors) {
        children.push(para(`✗ ${e.original}`, { color: 'dc2626' }));
        children.push(para(`→ ${e.correction}`, { color: '16a34a' }));
        if (e.explanation) children.push(para(`  ${e.explanation}`, { size: 18, color: '666666' }));
      }
      children.push(sep());
    }

    // AI Feedback
    if (a.generalComment) {
      children.push(heading('💡 AI Feedback', HeadingLevel.HEADING_2));
      children.push(para(String(a.generalComment)));
      if (a.generalCommentZh) {
        children.push(para(String(a.generalCommentZh), { size: 18, color: '666666' }));
      }
      children.push(sep());
    }

    // Improvement Tips
    const tips = (a.improvementTips as string[]) || [];
    if (tips.length) {
      children.push(heading('📈 Improvement Tips', HeadingLevel.HEADING_2));
      for (const tip of tips) children.push(para(`• ${tip}`));
      children.push(sep());
    }

    // Model Answer
    if (a.modelAnswer) {
      children.push(heading('🏆 Model Answer (DSE Level 5)', HeadingLevel.HEADING_1));
      children.push(new Paragraph({
        children: [new TextRun(String(a.modelAnswer))],
        spacing: { after: 200 },
        border: { left: { style: BorderStyle.SINGLE, color: '7c3aed', size: 6 } },
      }));
    }
  }

  const doc = new Document({ sections: [{ properties: {}, children }] });
  return Buffer.from(await Packer.toBuffer(doc));
}

export async function POST(request: NextRequest) {
  try {
    const data: ExportData = await request.json();
    if (!data.studentWriting && !data.analysis) {
      return NextResponse.json({ error: 'No content to export' }, { status: 400 });
    }

    const docxBuffer = await generateDOCX(data);
    return new NextResponse(new Uint8Array(docxBuffer), {
      headers: {
        'Content-Type': 'application/vnd.openxmlformats-officedocument.wordprocessingml.document',
        'Content-Disposition': 'attachment; filename="integrated-skills-report.docx"',
      },
    });
  } catch (error) {
    logger.error({ module: 'export-is', error: (error as Error).message }, 'Export failed');
    return NextResponse.json({ error: 'Export failed: ' + (error as Error).message }, { status: 500 });
  }
}
