// ============================================
// POST /api/export/integrated-skills
// 匯出 Integrated Skills 完整報告 (PDF)
// 包含：聆聽原文、Data File、筆記指引、學生筆記、學生寫作、AI 分析、範本答案
// ============================================

import { NextRequest, NextResponse } from 'next/server';
import { verifyApiAuth } from '@/shared/auth/api-auth';
import { logger } from '@/shared/logger/logger';

interface ExportData {
  listeningContent?: string;
  dataFileSources?: { type: string; title: string; content: string }[];
  noteTakingGuide?: { question: string; hint: string; questionZh?: string; hintZh?: string }[];
  writingTask?: string;
  taskType?: string;
  studentNotes?: string;
  studentWriting?: string;
  analysis?: {
    overallScore: number;
    listeningAccuracy?: number;
    contentCompleteness?: number;
    languageAccuracy?: number;
    organizationClarity?: number;
    capturedPoints?: string[];
    missedPoints?: string[];
    overCopyWarnings?: { original: string; suggestion: string }[];
    grammarErrors?: { original: string; correction: string; explanation: string }[];
    vocabularySuggestions?: { original: string; suggestion: string; reason: string }[];
    structureFeedback?: string;
    generalComment?: string;
    improvementTips?: string[];
    estimatedLevel?: string;
    modelAnswer?: string;
    noteTakingFeedback?: string;
    dataManipulationFeedback?: string;
  };
}

function loadCJKFont(): Buffer {
  const path = require('node:path') as typeof import('node:path');
  const fs = require('node:fs') as typeof import('node:fs');
  const bundled = path.join(process.cwd(), 'public', 'fonts', 'NotoSansTC-Regular.ttf');
  if (fs.existsSync(bundled)) return fs.readFileSync(bundled);

  const candidates = [
    'C:\\Windows\\Fonts\\msjh.ttc',
    '/usr/share/fonts/truetype/noto/NotoSansCJK-Regular.ttc',
  ];
  for (const fontPath of candidates) {
    try {
      if (fs.existsSync(fontPath)) return fs.readFileSync(fontPath);
    } catch { /* continue */ }
  }
  throw new Error('PDF 匯出需要字型檔。請執行 npx tsx scripts/download-font.ts 下載字型。');
}

function wrapText(
  doc: PDFKit.PDFDocument,
  text: string,
  x: number,
  y: number,
  maxWidth: number,
  lineHeight: number,
): number {
  const words = text.split('');
  let line = '';
  let currentY = y;

  for (const char of words) {
    const testLine = line + char;
    if (doc.widthOfString(testLine) > maxWidth && line.length > 0) {
      doc.text(line, x, currentY);
      currentY += lineHeight;
      line = char;
    } else {
      line = testLine;
    }
  }
  if (line) {
    doc.text(line, x, currentY);
    currentY += lineHeight;
  }
  return currentY;
}

async function generatePDF(data: ExportData): Promise<Buffer> {
  const PDFDocument = (await import('pdfkit')).default;
  type PDFKit = typeof import('pdfkit');

  return new Promise((resolve, reject) => {
    const chunks: Buffer[] = [];
    const doc = new PDFDocument({
      size: 'A4',
      margins: { top: 40, bottom: 40, left: 50, right: 50 },
      bufferPages: true,
    });

    doc.on('data', (chunk: Buffer) => chunks.push(chunk));
    doc.on('end', () => resolve(Buffer.concat(chunks)));
    doc.on('error', reject);

    const font = loadCJKFont();
    doc.registerFont('CJK', font);

    let y = 40;
    const lh = 14;
    const ml = 50;
    const mr = 50;
    const pageW = 595;
    const contentW = pageW - ml - mr;

    const checkPageBreak = (needed: number) => {
      if (y + needed > 800) {
        doc.addPage();
        y = 40;
      }
    };

    // Title
    doc.font('CJK', 18).text('DSE Integrated Skills Report', ml, y);
    y += 24;
    doc.font('CJK', 11).text('Generated by AI English Platform', ml, y);
    doc.moveTo(ml, y + 18).lineTo(ml + contentW, y + 18).stroke('#cccccc');
    y += 28;

    // ---- Section: Writing Task ----
    checkPageBreak(80);
    doc.font('CJK', 13).fillColor('#0891b2').text('Writing Task', ml, y);
    y += 18;
    doc.font('CJK', 10).fillColor('#333333');
    if (data.taskType) {
      doc.text(`Type: ${data.taskType}`, ml, y);
      y += lh;
    }
    if (data.writingTask) {
      y = wrapText(doc, data.writingTask, ml, y, contentW, lh) + 8;
    }

    // ---- Section: Listening Content ----
    if (data.listeningContent) {
      checkPageBreak(80);
      y += 4;
      doc.font('CJK', 13).fillColor('#0891b2').text('Listening Content', ml, y);
      y += 18;
      doc.font('CJK', 8).fillColor('#666666');
      y = wrapText(doc, data.listeningContent, ml, y, contentW, 10) + 8;
    }

    // ---- Section: Data File ----
    if (data.dataFileSources && data.dataFileSources.length > 0) {
      checkPageBreak(60);
      doc.font('CJK', 13).fillColor('#0891b2').text('Data File', ml, y);
      y += 18;
      for (const src of data.dataFileSources) {
        checkPageBreak(60);
        doc.font('CJK', 10).fillColor('#0891b2').text(`[${src.type}] ${src.title}`, ml, y);
        y += lh;
        doc.font('CJK', 8).fillColor('#666666');
        y = wrapText(doc, src.content, ml, y, contentW, 10) + 8;
      }
    }

    // ---- Section: Note-taking Guide ----
    if (data.noteTakingGuide && data.noteTakingGuide.length > 0) {
      checkPageBreak(60);
      doc.font('CJK', 13).fillColor('#0891b2').text('Note-taking Guide', ml, y);
      y += 18;
      doc.font('CJK', 10).fillColor('#333333');
      for (const item of data.noteTakingGuide) {
        checkPageBreak(30);
        doc.text(`${item.question}`, ml, y);
        y += lh;
        doc.font('CJK', 8).fillColor('#999999');
        doc.text(`Hint: ${item.hint}`, ml + 10, y);
        y += 12;
        if (item.questionZh) {
          doc.text(`中文: ${item.questionZh}`, ml + 10, y);
          y += 12;
        }
        doc.font('CJK', 10).fillColor('#333333');
      }
    }

    // ---- Section: Student Notes ----
    if (data.studentNotes) {
      checkPageBreak(60);
      y += 4;
      doc.font('CJK', 13).fillColor('#f59e0b').text('Student Note-taking', ml, y);
      y += 18;
      doc.font('CJK', 10).fillColor('#333333');
      y = wrapText(doc, data.studentNotes, ml, y, contentW, lh) + 8;
    }

    // ---- Section: Student Writing ----
    if (data.studentWriting) {
      checkPageBreak(60);
      y += 4;
      doc.font('CJK', 13).fillColor('#7c3aed').text('Student Writing', ml, y);
      y += 18;
      doc.font('CJK', 10).fillColor('#333333');
      y = wrapText(doc, data.studentWriting, ml, y, contentW, lh) + 8;
    }

    // ---- Section: AI Analysis ----
    if (data.analysis) {
      const a = data.analysis;
      checkPageBreak(80);
      y += 8;
      doc.font('CJK', 15).fillColor('#059669').text('AI Analysis', ml, y);
      y += 22;

      // Scores table
      const scores = [
        ['Overall Score', `${a.overallScore}%`],
        ['Listening Accuracy', `${a.listeningAccuracy ?? '-'}%`],
        ['Content Completeness', `${a.contentCompleteness ?? '-'}%`],
        ['Language Accuracy', `${a.languageAccuracy ?? '-'}%`],
        ['Organization & Clarity', `${a.organizationClarity ?? '-'}%`],
      ];
      doc.font('CJK', 10);
      for (const [label, val] of scores) {
        checkPageBreak(20);
        doc.fillColor('#333333').text(label, ml, y);
        doc.fillColor('#059669').text(val, ml + 200, y);
        y += lh;
      }
      if (a.estimatedLevel) {
        doc.fillColor('#333333').text('Estimated Level', ml, y);
        doc.fillColor('#059669').text(a.estimatedLevel, ml + 200, y);
        y += lh;
      }
      y += 8;

      // Captured/Missed Points
      if (a.capturedPoints?.length) {
        checkPageBreak(50);
        doc.font('CJK', 11).fillColor('#16a34a').text('Captured Points', ml, y);
        y += 16;
        doc.font('CJK', 9).fillColor('#333333');
        for (const pt of a.capturedPoints) {
          checkPageBreak(20);
          doc.text(`✓ ${pt}`, ml + 5, y);
          y += lh;
        }
        y += 4;
      }
      if (a.missedPoints?.length) {
        checkPageBreak(50);
        doc.font('CJK', 11).fillColor('#dc2626').text('Missed Points', ml, y);
        y += 16;
        doc.font('CJK', 9).fillColor('#333333');
        for (const pt of a.missedPoints) {
          checkPageBreak(20);
          doc.text(`✗ ${pt}`, ml + 5, y);
          y += lh;
        }
        y += 4;
      }

      // Grammar errors
      if (a.grammarErrors?.length) {
        checkPageBreak(60);
        doc.font('CJK', 11).fillColor('#dc2626').text('Grammar Errors', ml, y);
        y += 16;
        for (const e of a.grammarErrors) {
          checkPageBreak(40);
          doc.font('CJK', 9).fillColor('#dc2626');
          doc.text(`✗ ${e.original}`, ml + 5, y);
          y += 12;
          doc.fillColor('#16a34a');
          doc.text(`→ ${e.correction}`, ml + 10, y);
          y += 12;
          if (e.explanation) {
            doc.font('CJK', 8).fillColor('#666666');
            doc.text(`   ${e.explanation}`, ml + 10, y);
            y += 10;
          }
          y += 4;
        }
      }

      // AI Feedback
      if (a.generalComment) {
        checkPageBreak(60);
        y += 4;
        doc.font('CJK', 11).fillColor('#2563eb').text('AI Feedback', ml, y);
        y += 16;
        doc.font('CJK', 10).fillColor('#333333');
        y = wrapText(doc, a.generalComment, ml, y, contentW, lh) + 8;
      }

      // Improvement Tips
      if (a.improvementTips?.length) {
        checkPageBreak(60);
        doc.font('CJK', 11).fillColor('#16a34a').text('Improvement Tips', ml, y);
        y += 16;
        doc.font('CJK', 9).fillColor('#333333');
        for (const tip of a.improvementTips) {
          checkPageBreak(20);
          doc.text(`• ${tip}`, ml + 5, y);
          y += lh;
        }
        y += 4;
      }

      // Model Answer
      if (a.modelAnswer) {
        checkPageBreak(60);
        y += 4;
        doc.font('CJK', 13).fillColor('#7c3aed').text('Model Answer (DSE Level 5)', ml, y);
        y += 18;
        doc.font('CJK', 10).fillColor('#333333');
        y = wrapText(doc, a.modelAnswer, ml, y, contentW, lh) + 8;
      }
    }

    doc.end();
  });
}

export async function POST(request: NextRequest) {
  try {
    // Auth check (optional — allow unauthenticated for classroom use)
    // const auth = await verifyApiAuth(request);
    // if (!auth.ok) return auth.error;

    const data: ExportData = await request.json();
    if (!data.studentWriting && !data.analysis) {
      return NextResponse.json({ error: 'No content to export' }, { status: 400 });
    }

    const format = request.nextUrl.searchParams.get('format') || 'pdf';

    if (format === 'pdf') {
      const pdfBuffer = await generatePDF(data);
      return new NextResponse(new Uint8Array(pdfBuffer), {
        headers: {
          'Content-Type': 'application/pdf',
          'Content-Disposition': 'attachment; filename="integrated-skills-report.pdf"',
        },
      });
    }

    return NextResponse.json({ error: `Unsupported format: ${format}` }, { status: 400 });
  } catch (error) {
    logger.error({ module: 'export-is', error: (error as Error).message }, 'Export failed');
    return NextResponse.json({ error: 'Export failed' }, { status: 500 });
  }
}
