// ============================================
// POST /api/export/integrated-skills
// 匯出 Integrated Skills 完整報告 (DOCX)
// ============================================

import { NextRequest, NextResponse } from 'next/server';
import { logger } from '@/shared/logger/logger';

interface ExportData {
  listeningContent?: string;
  dataFileSources?: { type: string; title: string; content: string }[];
  noteTakingGuide?: { question: string; hint: string; questionZh?: string; hintZh?: string }[];
  writingTask?: string; taskType?: string;
  studentNotes?: string; studentWriting?: string;
  analysis?: Record<string, unknown>;
}

async function generateDOCX(data: ExportData): Promise<Buffer> {
  const { Document, Packer, Paragraph, TextRun, HeadingLevel, Table, TableRow, TableCell, WidthType, BorderStyle } = await import('docx');
  const children: any[] = [];
  const h1 = (t: string) => new Paragraph({ heading: HeadingLevel.HEADING_1, children: [new TextRun(t)], spacing: { before: 300, after: 100 } });
  const h2 = (t: string, c?: string) => new Paragraph({ heading: HeadingLevel.HEADING_2, children: [new TextRun({ text: t, color: c || '000000' })], spacing: { before: 200, after: 80 } });
  const p = (t: string, o?: any) => new Paragraph({ children: [new TextRun({ text: t, ...o })], spacing: { after: 80 } });
  const sep = () => { children.push(new Paragraph({ spacing: { after: 120 }, children: [] })); };

  children.push(new Paragraph({ heading: HeadingLevel.TITLE, children: [new TextRun('DSE Integrated Skills Report')], spacing: { after: 100 } }));
  children.push(p('Generated by AI English Platform', { italics: true, color: '888888', size: 20 }));
  sep();

  if (data.writingTask) { children.push(h1('Writing Task')); children.push(p(`Type: ${data.taskType || 'N/A'}`)); children.push(p(data.writingTask)); sep(); }
  if (data.listeningContent) { children.push(h1('Listening Content')); children.push(p(data.listeningContent, { size: 18, color: '666666' })); sep(); }

  // Data File
  if (data.dataFileSources?.length) {
    children.push(h1('Data File'));
    for (const src of data.dataFileSources) {
      children.push(h2(`[${src.type}] ${src.title}`));
      children.push(p(src.content, { size: 18, color: '666666' }));
    }
    sep();
  }

  // Note-taking Guide
  if (data.noteTakingGuide?.length) {
    children.push(h1('Note-taking Guide'));
    for (const item of data.noteTakingGuide) {
      children.push(p(`Q: ${item.question}`, { bold: true }));
      children.push(p(`Hint: ${item.hint}`, { size: 18, color: '888888', italics: true }));
      if (item.questionZh) children.push(p(`[中] ${item.questionZh}`, { size: 18, color: '888888' }));
      if (item.hintZh) children.push(p(`[中] ${item.hintZh}`, { size: 18, color: '888888' }));
    }
    sep();
  }

  if (data.studentNotes) { children.push(h1('Student Note-taking')); children.push(new Paragraph({ children: [new TextRun(data.studentNotes)], border: { left: { style: BorderStyle.SINGLE, color: 'f59e0b', size: 6 } }, spacing: { after: 200 } })); sep(); }
  if (data.studentWriting) { children.push(h1('Student Writing')); children.push(new Paragraph({ children: [new TextRun(data.studentWriting)], border: { left: { style: BorderStyle.SINGLE, color: '7c3aed', size: 6 } }, spacing: { after: 200 } })); sep(); }

  const a = data.analysis;
  if (a) {
    children.push(h1('AI Analysis'));
    const scores: [string, string][] = [
      ['Overall Score', `${a.overallScore}%`], ['Listening Accuracy', `${a.listeningAccuracy ?? '-'}%`],
      ['Content Completeness', `${a.contentCompleteness ?? '-'}%`], ['Language Accuracy', `${a.languageAccuracy ?? '-'}%`],
      ['Organization & Clarity', `${a.organizationClarity ?? '-'}%`],
    ];
    if (a.estimatedLevel) scores.push(['Estimated Level', String(a.estimatedLevel)]);
    children.push(new Table({ rows: scores.map(([l, v]) => new TableRow({ children: [new TableCell({ children: [new Paragraph({ children: [new TextRun({ text: l, bold: true })], spacing: { after: 0 } })], width: { size: 4500, type: WidthType.DXA } }), new TableCell({ children: [new Paragraph({ children: [new TextRun(v)], spacing: { after: 0 } })] })] })), width: { size: 100, type: WidthType.PERCENTAGE } }));
    sep();

    const caps = (a.capturedPoints as string[]) || [], miss = (a.missedPoints as string[]) || [];
    if (caps.length) { children.push(h2(`Captured Points (${caps.length})`, '16a34a')); caps.forEach(pt => children.push(p(`✓ ${pt}`))); }
    if (miss.length) { children.push(h2(`Missed Points (${miss.length})`, 'dc2626')); miss.forEach(pt => children.push(p(`✗ ${pt}`))); }
    sep();

    const ge = (a.grammarErrors as any[]) || [];
    if (ge.length) { children.push(h2('Grammar Errors', 'dc2626')); ge.forEach(e => { children.push(p(`✗ ${e.original}`, { color: 'dc2626' })); children.push(p(`→ ${e.correction}`, { color: '16a34a' })); if (e.explanation) children.push(p(`  ${e.explanation}`, { size: 18, color: '666666' })); }); sep(); }

    if (a.generalComment) { children.push(h2('AI Feedback', '2563eb')); children.push(p(String(a.generalComment))); if (a.generalCommentZh) children.push(p(String(a.generalCommentZh), { size: 18, color: '666666' })); sep(); }
    const tips = (a.improvementTips as string[]) || [];
    if (tips.length) { children.push(h2('Improvement Tips', '16a34a')); tips.forEach(t => children.push(p(`• ${t}`))); sep(); }
    if (a.modelAnswer) { children.push(h1('Model Answer (DSE Level 5)')); children.push(new Paragraph({ children: [new TextRun(String(a.modelAnswer))], border: { left: { style: BorderStyle.SINGLE, color: '7c3aed', size: 6 } }, spacing: { after: 200 } })); }
  }

  return Buffer.from(await Packer.toBuffer(new Document({ sections: [{ properties: {}, children }] })));
}

export async function POST(request: NextRequest) {
  try {
    const data: ExportData = await request.json();
    if (!data.studentWriting && !data.analysis) {
      return NextResponse.json({ error: 'No content to export' }, { status: 400 });
    }
    const buf = await generateDOCX(data);
    return new NextResponse(new Uint8Array(buf), {
      headers: { 'Content-Type': 'application/vnd.openxmlformats-officedocument.wordprocessingml.document', 'Content-Disposition': 'attachment; filename="integrated-skills-report.docx"' },
    });
  } catch (error) {
    logger.error({ module: 'export-is', error: (error as Error).message }, 'Export failed');
    return NextResponse.json({ error: 'Export failed: ' + (error as Error).message }, { status: 500 });
  }
}
